addEventListener(DOMContentLoaded)

let cell1 = document.getElementById('1-1')
let cell2 = document.getElementById('1-2')
let cell3 = document.getElementById('1-3')
let cell4 = document.getElementById('1-4')
let cell5 = document.getElementById('1-5')
let cell6 = document.getElementById('2-1')
let cell7 = document.getElementById('2-2')
let cell8 = document.getElementById('2-3')
let cell9 = document.getElementById('2-4')
let cell10 = document.getElementById('2-5')
let cell11 = document.getElementById('3-1')
let cell12 = document.getElementById('3-2')
let cell13 = document.getElementById('3-3')
let cell14 = document.getElementById('3-4')
let cell15 = document.getElementById('3-5')
let cell16 = document.getElementById('4-1')
let cell17 = document.getElementById('4-2')
let cell18 = document.getElementById('4-3')
let cell19 = document.getElementById('4-4')
let cell20 = document.getElementById('4-5')
let cell21 = document.getElementById('5-1')
let cell22 = document.getElementById('5-2')
let cell23 = document.getElementById('5-3')
let cell24 = document.getElementById('5-4')
let cell25 = document.getElementById('5-5')

